### ISSUE TITLE
Build Fails

### ISSUE THREAD

**Issue by athul** [athul/OSC--Website#6]
Hey @akzhy  any Idea why the build fails? Really need to redesign this stuff from the ground up I guess?

**Comment by athul** [comment]
```
Installing build runtime...
Build runtime installed: 920.475ms
Looking up build cache...
Installing dependencies...
yarn install v1.17.3
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "gatsby-plugin-less > less-loader@4.1.0" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
[4/4] Building fresh packages...
Done in 49.84s.
Running "yarn run build"
yarn run v1.17.3
$ gatsby build
╔════════════════════════════════════════════════════════════════════════╗
║                                                                        ║
║   Gatsby has started collecting anonymous usage analytics              ║
║   to help improve Gatsby for all users.                                ║
║                                                                        ║
║   If you'd like to opt-out, you can use `gatsby telemetry --disable`   ║
║   To learn more, checkout https://gatsby.dev/telemetry                 ║
║                                                                        ║
╚════════════════════════════════════════════════════════════════════════╝

[2K[1A[2K[G⠋ open and validate gatsby-configs
[2K[1A[2K[G
success open and validate gatsby-configs - 0.025 s
⠋ open and validate gatsby-configs
[2K[1A[2K[G
[2K[1A[2K[G⠋ load plugins
[2K[1A[2K[Gsuccess load plugins - 0.572 s
⠋ load plugins
[2K[1A[2K[G
[2K[1A[2K[G⠋ onPreInit
[2K[1A[2K[G
success onPreInit - 0.009 s
⠋ onPreInit
[2K[1A[2K[G
[2K[1A[2K[G⠋ delete html and css files from previous builds
[2K[1A[2K[G
success delete html and css files from previous builds - 0.010 s
⠋ delete html and css files from previous builds
[2K[1A[2K[G
[2K[1A[2K[G⠋ initialize cache
[2K[1A[2K[Gsuccess initialize cache - 0.012 s
⠋ initialize cache
[2K[1A[2K[G
[2K[1A[2K[G⠋ copy gatsby files
[2K[1A[2K[G
success copy gatsby files - 0.021 s
⠋ copy gatsby files
[2K[1A[2K[G
[2K[1A[2K[G⠋ onPreBootstrap
[2K[1A[2K[G
success onPreBootstrap - 0.022 s
⠋ onPreBootstrap
[2K[1A[2K[G
[2K[1A[2K[G⠋ source and transform nodes
[2K[1A[2K[G⠙ source and transform nodes
[2K[1A[2K[G
success source and transform nodes - 0.119 s
⠙ source and transform nodes
[2K[1A[2K[G
[2K[1A[2K[G⠋ building schema
[2K[1A[2K[G⠙ building schema
[2K[1A[2K[G
success building schema - 0.299 s
⠙ building schema
[2K[1A[2K[G
[2K[1A[2K[G⠋ createPages
[2K[1A[2K[G
success createPages - 0.053 s
⠋ createPages
[2K[1A[2K[G
[2K[1A[2K[G⠋ createPagesStatefully
[2K[1A[2K[G
success createPagesStatefully - 0.032 s
⠋ createPagesStatefully
[2K[1A[2K[G
[2K[1A[2K[G⠋ onPreExtractQueries
[2K[1A[2K[G
success onPreExtractQueries - 0.010 s
⠋ onPreExtractQueries
[2K[1A[2K[G
[2K[1A[2K[G⠋ update schema
[2K[1A[2K[G
success update schema - 0.037 s
⠋ update schema
[2K[1A[2K[G
[2K[1A[2K[G⠋ extract queries from components
[2K[1A[2K[G⠙ extract queries from components
[2K[1A[2K[G

 ERROR #85909  GRAPHQL

Field "banner" must not have a selection since type "String" has no subfields

File: src/templates/blog.js:55:11

⠙ extract queries from components
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Exited with 1
    at ChildProcess.child.on (/tmp/40f9385d99dd2d94/.build-utils/.builder/node_modules/@now/static-build/dist/index.js:23548:24)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
worker exited with code 20 and signal null
done
```

**Comment by akzhy** [comment]
Missing the banner image for blog item

**Comment by athul** [comment]
I had updated that. Check the new version.

**Comment by akzhy** [comment]
I need console messages

**Comment by athul** [comment]
```bash
success update schema - 0.060 s
warn The GraphQL query in the non-page component
"/Users/athul/Desktop/CCC-Website/src/templates/blog-list.js" will not be run.
warn The GraphQL query in the non-page component
"/Users/athul/Desktop/CCC-Website/src/templates/blog.js" will not be run.
Exported queries are only executed for Page components. It's possible you're
trying to create pages in your gatsby-node.js and that's failing for some
reason.

If the failing component(s) is a regular component and not intended to be a page
component, you generally want to use a <StaticQuery> (https://gatsbyjs.org/docs/static-query)
instead of exporting a page query.

If you're more experienced with GraphQL, you can also export GraphQL
fragments from components and compose the fragments in the Page component
query and pass data down into the child component — http://graphql.org/learn/queries/#fragments
success extract queries from components - 0.745 s
```
